import type { Activity, Employee, EmployeeId, Product } from "./types";

export const employees: Record<EmployeeId, Employee> = {
  neia: {
    id: "neia",
    name: "Neia",
    schedule: "06:30 às 15:30",
    lunch: "13:00 às 14:00",
    saturday: "06:30 às 10:30",
  },
  selma: {
    id: "selma",
    name: "Selma",
    schedule: "07:00 às 16:00",
    lunch: "12:30 às 13:30",
    saturday: "08:00 às 12:00",
  },
  helena: {
    id: "helena",
    name: "Helena",
    schedule: "08:00 às 18:00",
    lunch: "12:00 às 13:00",
    saturday: "Não trabalha",
  },
};

export const activities: Activity[] = [
  {
    id: "neia-1",
    employeeId: "neia",
    pavimento: "Térreo",
    ambiente: "Recepção",
    atividade: "Varrer, passar pano e organizar área de entrada",
    frequencia: "Diária",
  },
  {
    id: "neia-2",
    employeeId: "neia",
    pavimento: "Térreo",
    ambiente: "Banheiros",
    atividade: "Higienizar vasos, pias, espelhos e repor materiais",
    frequencia: "Diária",
  },
  {
    id: "neia-3",
    employeeId: "neia",
    pavimento: "1º pavimento",
    ambiente: "Salas de atendimento",
    atividade: "Limpar mesas, retirar lixo e organizar cadeiras",
    frequencia: "Diária",
  },
  {
    id: "neia-4",
    employeeId: "neia",
    pavimento: "Geral",
    ambiente: "Materiais",
    atividade: "Conferir itens de limpeza para pedido Sinval",
    frequencia: "Semanal",
  },
  {
    id: "selma-1",
    employeeId: "selma",
    pavimento: "1º pavimento",
    ambiente: "Corredores",
    atividade: "Varrer, passar pano e recolher resíduos",
    frequencia: "Diária",
  },
  {
    id: "selma-2",
    employeeId: "selma",
    pavimento: "1º pavimento",
    ambiente: "Copa",
    atividade: "Limpar bancada, pia, piso e recolher lixo",
    frequencia: "Diária",
  },
  {
    id: "selma-3",
    employeeId: "selma",
    pavimento: "2º pavimento",
    ambiente: "Banheiros",
    atividade: "Higienizar banheiros e repor papel quando necessário",
    frequencia: "Diária",
  },
  {
    id: "selma-4",
    employeeId: "selma",
    pavimento: "Geral",
    ambiente: "Vidros e portas",
    atividade: "Limpar marcas visíveis em portas e divisórias",
    frequencia: "Semanal",
  },
  {
    id: "helena-1",
    employeeId: "helena",
    pavimento: "2º pavimento",
    ambiente: "Salas administrativas",
    atividade: "Limpar estações de trabalho e retirar lixo",
    frequencia: "Diária",
  },
  {
    id: "helena-2",
    employeeId: "helena",
    pavimento: "2º pavimento",
    ambiente: "Sala de reunião",
    atividade: "Organizar mesa, cadeiras e higienizar superfícies",
    frequencia: "Diária",
  },
  {
    id: "helena-3",
    employeeId: "helena",
    pavimento: "Geral",
    ambiente: "Escadas",
    atividade: "Varrer degraus, corrimãos e retirar pó acumulado",
    frequencia: "Diária",
  },
  {
    id: "helena-4",
    employeeId: "helena",
    pavimento: "Geral",
    ambiente: "Áreas de apoio",
    atividade: "Limpeza reforçada de cantos e rodapés",
    frequencia: "Semanal",
  },
];

export const products: Product[] = [
  { id: "agua-sanitaria", name: "Água Sanitária", unit: "Litro" },
  { id: "alcool-comum", name: "Álcool Comum", unit: "Litro" },
  { id: "alcool-gel", name: "Álcool Gel", unit: "Galão" },
  { id: "bom-ar", name: "Bom Ar", unit: "Unidade" },
  { id: "copo-descartavel-200ml", name: "Copo Descartável 200ml", unit: "Caixa" },
  { id: "detergente", name: "Detergente", unit: "Unidade" },
  { id: "esponja", name: "Esponja", unit: "Unidade" },
  { id: "flanela", name: "Flanela", unit: "Unidade" },
  { id: "luva", name: "Luva", unit: "Par" },
  { id: "pano-de-chao", name: "Pano de Chão", unit: "Unidade" },
  { id: "papel-higienico", name: "Papel Higiênico", unit: "Fardo" },
  { id: "papel-toalha", name: "Papel Toalha", unit: "Caixa" },
  { id: "perfex", name: "Perfex", unit: "Rolo" },
  { id: "querosene", name: "Querosene", unit: "Litro" },
  { id: "rajalim", name: "Rajalim", unit: "Litro" },
  { id: "sabao-em-barra", name: "Sabão em Barra", unit: "Pacote" },
  { id: "sabao-em-po", name: "Sabão em Pó", unit: "Caixa" },
  { id: "sabonete-liquido", name: "Sabonete Líquido", unit: "Galão" },
  { id: "saco-lixo-20l", name: "Saco de Lixo 20L", unit: "Unidade/Pacote" },
  { id: "saco-lixo-60l", name: "Saco de Lixo 60L", unit: "Unidade/Pacote" },
  { id: "saco-lixo-100l", name: "Saco de Lixo 100L", unit: "Unidade/Pacote" },
  { id: "veneno", name: "Veneno", unit: "Unidade" },
  { id: "sactif-multiuso-5l", name: "Sactif Mult Uso 5L", unit: "Galão" },
];
