create table if not exists public.marketing_teams (
  id uuid primary key default gen_random_uuid(),
  manager_name text not null unique check (btrim(manager_name) <> ''),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketing_brokers (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.marketing_teams(id) on delete restrict,
  name text not null check (btrim(name) <> ''),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists marketing_brokers_team_name_uidx
  on public.marketing_brokers(team_id, lower(btrim(name)));

create table if not exists public.marketing_access (
  managed_user_id text primary key references public.managed_users(id) on update cascade on delete cascade,
  role text not null check (role in ('admin', 'marketing', 'sales_manager')),
  team_id uuid references public.marketing_teams(id) on delete restrict,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (role <> 'sales_manager' or team_id is not null)
);

create table if not exists public.marketing_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  team_id uuid not null references public.marketing_teams(id) on delete restrict,
  manager_name text not null check (btrim(manager_name) <> ''),
  broker_id uuid references public.marketing_brokers(id) on delete set null,
  broker_name text not null check (btrim(broker_name) <> ''),
  has_property_code boolean not null default true,
  property_reference text not null check (btrim(property_reference) <> ''),
  request_kind text not null check (request_kind in ('capture_edit', 'edit_only')),
  content_types text[] not null default '{}'::text[] check (cardinality(content_types) > 0),
  capture_location text,
  preferred_capture_at timestamptz,
  confirmed_capture_at timestamptz,
  asset_link text,
  paid_traffic boolean not null default false,
  requester_notes text,
  marketing_notes text,
  status text not null default 'solicitado'
    check (status in ('solicitado', 'agendado', 'aguardando_edicao', 'em_edicao', 'em_aprovacao', 'revisao', 'pronto', 'bloqueado', 'cancelado')),
  assigned_marketing_name text,
  promised_at timestamptz,
  urgency_requested boolean not null default false,
  urgency_reason text,
  urgency_approved boolean not null default false,
  urgency_decided_by_name text,
  urgency_decided_at timestamptz,
  created_by_user_id text not null references public.managed_users(id) on update cascade on delete restrict,
  created_by_name text not null check (btrim(created_by_name) <> ''),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (not urgency_requested or nullif(btrim(coalesce(urgency_reason, '')), '') is not null)
);

create index if not exists marketing_requests_queue_idx
  on public.marketing_requests(urgency_approved desc, created_at asc)
  where status not in ('pronto', 'cancelado');
create index if not exists marketing_requests_team_idx
  on public.marketing_requests(team_id, created_at desc);
create index if not exists marketing_requests_capture_idx
  on public.marketing_requests(confirmed_capture_at)
  where confirmed_capture_at is not null and status <> 'cancelado';

create table if not exists public.marketing_request_events (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.marketing_requests(id) on delete restrict,
  event_type text not null check (btrim(event_type) <> ''),
  from_status text,
  to_status text,
  actor_user_id text references public.managed_users(id) on update cascade on delete set null,
  actor_name text not null check (btrim(actor_name) <> ''),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists marketing_request_events_request_idx
  on public.marketing_request_events(request_id, created_at desc);

create or replace function public.touch_marketing_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists marketing_teams_touch on public.marketing_teams;
create trigger marketing_teams_touch before update on public.marketing_teams
for each row execute function public.touch_marketing_updated_at();
drop trigger if exists marketing_brokers_touch on public.marketing_brokers;
create trigger marketing_brokers_touch before update on public.marketing_brokers
for each row execute function public.touch_marketing_updated_at();
drop trigger if exists marketing_access_touch on public.marketing_access;
create trigger marketing_access_touch before update on public.marketing_access
for each row execute function public.touch_marketing_updated_at();
drop trigger if exists marketing_requests_touch on public.marketing_requests;
create trigger marketing_requests_touch before update on public.marketing_requests
for each row execute function public.touch_marketing_updated_at();

insert into public.marketing_teams (manager_name, sort_order)
values
  ('Fernando', 10),
  ('Fabio', 20),
  ('Peres', 30),
  ('Angela', 40),
  ('Cacilda', 50),
  ('Andreia', 60)
on conflict (manager_name) do update
set sort_order = excluded.sort_order,
    active = true;

insert into public.marketing_access (managed_user_id, role, team_id, active)
select 'tezzei', 'admin', null, true
where exists (select 1 from public.managed_users where id = 'tezzei')
on conflict (managed_user_id) do update
set role = 'admin', team_id = null, active = true;

create or replace function public.marketing_resolve_actor(p_access_code text)
returns table (
  user_id text,
  user_name text,
  access_role text,
  team_id uuid
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    u.id,
    u.name,
    a.role,
    a.team_id
  from public.managed_users u
  join public.marketing_access a on a.managed_user_id = u.id and a.active is true
  where u.active is true
    and nullif(btrim(p_access_code), '') is not null
    and u.access_code_hash = extensions.crypt(btrim(p_access_code), u.access_code_hash)
  limit 1;
$$;

create or replace function public.marketing_get_dashboard(p_access_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id text;
  v_user_name text;
  v_role text;
  v_team_id uuid;
  v_team_name text;
  v_result jsonb;
begin
  select r.user_id, r.user_name, r.access_role, r.team_id
    into v_user_id, v_user_name, v_role, v_team_id
  from public.marketing_resolve_actor(p_access_code) r;

  if v_user_id is null then
    raise exception 'MARKETING_ACCESS_DENIED';
  end if;

  select t.manager_name into v_team_name
  from public.marketing_teams t
  where t.id = v_team_id;

  select jsonb_build_object(
    'context', jsonb_build_object(
      'userId', v_user_id,
      'userName', v_user_name,
      'role', v_role,
      'teamId', v_team_id,
      'teamName', v_team_name
    ),
    'teams', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', t.id,
        'managerName', t.manager_name,
        'active', t.active,
        'sortOrder', t.sort_order
      ) order by t.sort_order, t.manager_name)
      from public.marketing_teams t
      where t.active is true
        and (v_role <> 'sales_manager' or t.id = v_team_id)
    ), '[]'::jsonb),
    'brokers', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', b.id,
        'teamId', b.team_id,
        'name', b.name,
        'active', b.active
      ) order by b.name)
      from public.marketing_brokers b
      where b.active is true
        and (v_role <> 'sales_manager' or b.team_id = v_team_id)
    ), '[]'::jsonb),
    'requests', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', q.id,
        'requestNumber', q.request_number,
        'teamId', q.team_id,
        'managerName', q.manager_name,
        'brokerId', q.broker_id,
        'brokerName', q.broker_name,
        'hasPropertyCode', q.has_property_code,
        'propertyReference', q.property_reference,
        'requestKind', q.request_kind,
        'contentTypes', q.content_types,
        'captureLocation', q.capture_location,
        'preferredCaptureAt', q.preferred_capture_at,
        'confirmedCaptureAt', q.confirmed_capture_at,
        'assetLink', q.asset_link,
        'paidTraffic', q.paid_traffic,
        'requesterNotes', q.requester_notes,
        'marketingNotes', q.marketing_notes,
        'status', q.status,
        'assignedMarketingName', q.assigned_marketing_name,
        'promisedAt', q.promised_at,
        'urgencyRequested', q.urgency_requested,
        'urgencyReason', q.urgency_reason,
        'urgencyApproved', q.urgency_approved,
        'urgencyDecidedByName', q.urgency_decided_by_name,
        'urgencyDecidedAt', q.urgency_decided_at,
        'createdByUserId', q.created_by_user_id,
        'createdByName', q.created_by_name,
        'completedAt', q.completed_at,
        'createdAt', q.created_at,
        'updatedAt', q.updated_at
      ) order by q.urgency_approved desc, q.created_at asc)
      from public.marketing_requests q
      where (v_role <> 'sales_manager' or q.team_id = v_team_id)
    ), '[]'::jsonb),
    'access', case when v_role = 'admin' then coalesce((
      select jsonb_agg(jsonb_build_object(
        'managedUserId', a.managed_user_id,
        'userName', u.name,
        'role', a.role,
        'teamId', a.team_id,
        'active', a.active
      ) order by u.name)
      from public.marketing_access a
      join public.managed_users u on u.id = a.managed_user_id
    ), '[]'::jsonb) else '[]'::jsonb end,
    'availableUsers', case when v_role = 'admin' then coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', u.id,
        'name', u.name,
        'jobTitle', u.job_title,
        'department', u.department,
        'active', u.active
      ) order by u.name)
      from public.managed_users u
      where u.active is true
    ), '[]'::jsonb) else '[]'::jsonb end
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.marketing_create_request(
  p_access_code text,
  p_team_id uuid,
  p_broker_name text,
  p_has_property_code boolean,
  p_property_reference text,
  p_request_kind text,
  p_content_types text[],
  p_capture_location text default null,
  p_preferred_capture_at timestamptz default null,
  p_asset_link text default null,
  p_paid_traffic boolean default false,
  p_requester_notes text default null,
  p_urgency_requested boolean default false,
  p_urgency_reason text default null
)
returns table (request_id uuid, request_number bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id text;
  v_user_name text;
  v_role text;
  v_actor_team_id uuid;
  v_manager_name text;
  v_broker_id uuid;
  v_request_id uuid;
  v_request_number bigint;
begin
  select r.user_id, r.user_name, r.access_role, r.team_id
    into v_user_id, v_user_name, v_role, v_actor_team_id
  from public.marketing_resolve_actor(p_access_code) r;

  if v_user_id is null or v_role not in ('admin', 'sales_manager') then
    raise exception 'MARKETING_CREATE_DENIED';
  end if;
  if v_role = 'sales_manager' and p_team_id is distinct from v_actor_team_id then
    raise exception 'MARKETING_TEAM_DENIED';
  end if;
  if nullif(btrim(coalesce(p_broker_name, '')), '') is null then
    raise exception 'MARKETING_BROKER_REQUIRED';
  end if;
  if nullif(btrim(coalesce(p_property_reference, '')), '') is null then
    raise exception 'MARKETING_PROPERTY_REQUIRED';
  end if;
  if p_request_kind not in ('capture_edit', 'edit_only') then
    raise exception 'MARKETING_KIND_INVALID';
  end if;
  if coalesce(cardinality(p_content_types), 0) = 0 then
    raise exception 'MARKETING_CONTENT_REQUIRED';
  end if;
  if p_urgency_requested and nullif(btrim(coalesce(p_urgency_reason, '')), '') is null then
    raise exception 'MARKETING_URGENCY_REASON_REQUIRED';
  end if;

  select t.manager_name into v_manager_name
  from public.marketing_teams t
  where t.id = p_team_id and t.active is true;
  if v_manager_name is null then
    raise exception 'MARKETING_TEAM_NOT_FOUND';
  end if;

  select b.id into v_broker_id
  from public.marketing_brokers b
  where b.team_id = p_team_id
    and lower(btrim(b.name)) = lower(btrim(p_broker_name))
  limit 1;

  if v_broker_id is null then
    insert into public.marketing_brokers (team_id, name)
    values (p_team_id, btrim(p_broker_name))
    returning id into v_broker_id;
  end if;

  insert into public.marketing_requests (
    team_id, manager_name, broker_id, broker_name,
    has_property_code, property_reference, request_kind, content_types,
    capture_location, preferred_capture_at, asset_link, paid_traffic,
    requester_notes, urgency_requested, urgency_reason,
    created_by_user_id, created_by_name
  ) values (
    p_team_id, v_manager_name, v_broker_id, btrim(p_broker_name),
    coalesce(p_has_property_code, true), btrim(p_property_reference), p_request_kind, p_content_types,
    nullif(btrim(coalesce(p_capture_location, '')), ''), p_preferred_capture_at,
    nullif(btrim(coalesce(p_asset_link, '')), ''), coalesce(p_paid_traffic, false),
    nullif(btrim(coalesce(p_requester_notes, '')), ''), coalesce(p_urgency_requested, false),
    nullif(btrim(coalesce(p_urgency_reason, '')), ''),
    v_user_id, v_user_name
  ) returning id, marketing_requests.request_number into v_request_id, v_request_number;

  insert into public.marketing_request_events (
    request_id, event_type, from_status, to_status, actor_user_id, actor_name, details
  ) values (
    v_request_id, 'criado', null, 'solicitado', v_user_id, v_user_name,
    jsonb_build_object('urgencyRequested', coalesce(p_urgency_requested, false))
  );

  return query select v_request_id, v_request_number;
end;
$$;

create or replace function public.marketing_update_request(
  p_access_code text,
  p_request_id uuid,
  p_action text,
  p_payload jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id text;
  v_user_name text;
  v_role text;
  v_actor_team_id uuid;
  v_request public.marketing_requests%rowtype;
  v_status text;
  v_confirmed timestamptz;
  v_promised timestamptz;
  v_assigned text;
  v_marketing_notes text;
begin
  select r.user_id, r.user_name, r.access_role, r.team_id
    into v_user_id, v_user_name, v_role, v_actor_team_id
  from public.marketing_resolve_actor(p_access_code) r;
  if v_user_id is null then raise exception 'MARKETING_ACCESS_DENIED'; end if;

  select * into v_request from public.marketing_requests where id = p_request_id for update;
  if v_request.id is null then raise exception 'MARKETING_REQUEST_NOT_FOUND'; end if;

  if p_action = 'cancel' then
    if v_role = 'sales_manager' and v_request.team_id is distinct from v_actor_team_id then
      raise exception 'MARKETING_REQUEST_DENIED';
    end if;
    if v_role not in ('admin', 'marketing', 'sales_manager') then raise exception 'MARKETING_REQUEST_DENIED'; end if;
    update public.marketing_requests
      set status = 'cancelado', completed_at = now()
      where id = p_request_id;
    insert into public.marketing_request_events(request_id, event_type, from_status, to_status, actor_user_id, actor_name, details)
      values (p_request_id, 'cancelado', v_request.status, 'cancelado', v_user_id, v_user_name, p_payload);
    return;
  end if;

  if p_action = 'approve_urgency' then
    if v_role <> 'admin' then raise exception 'MARKETING_URGENCY_DENIED'; end if;
    update public.marketing_requests
      set urgency_requested = true,
          urgency_approved = true,
          urgency_decided_by_name = v_user_name,
          urgency_decided_at = now()
      where id = p_request_id;
    insert into public.marketing_request_events(request_id, event_type, from_status, to_status, actor_user_id, actor_name, details)
      values (p_request_id, 'urgencia_aprovada', v_request.status, v_request.status, v_user_id, v_user_name, p_payload);
    return;
  end if;

  if p_action = 'reject_urgency' then
    if v_role <> 'admin' then raise exception 'MARKETING_URGENCY_DENIED'; end if;
    update public.marketing_requests
      set urgency_approved = false,
          urgency_decided_by_name = v_user_name,
          urgency_decided_at = now()
      where id = p_request_id;
    insert into public.marketing_request_events(request_id, event_type, from_status, to_status, actor_user_id, actor_name, details)
      values (p_request_id, 'urgencia_mantida_na_fila', v_request.status, v_request.status, v_user_id, v_user_name, p_payload);
    return;
  end if;

  if p_action <> 'save_management' or v_role not in ('admin', 'marketing') then
    raise exception 'MARKETING_UPDATE_DENIED';
  end if;

  v_status := coalesce(nullif(p_payload->>'status', ''), v_request.status);
  if v_status not in ('solicitado', 'agendado', 'aguardando_edicao', 'em_edicao', 'em_aprovacao', 'revisao', 'pronto', 'bloqueado', 'cancelado') then
    raise exception 'MARKETING_STATUS_INVALID';
  end if;
  v_confirmed := case when p_payload ? 'confirmedCaptureAt' then nullif(p_payload->>'confirmedCaptureAt', '')::timestamptz else v_request.confirmed_capture_at end;
  v_promised := case when p_payload ? 'promisedAt' then nullif(p_payload->>'promisedAt', '')::timestamptz else v_request.promised_at end;
  v_assigned := case when p_payload ? 'assignedMarketingName' then nullif(btrim(p_payload->>'assignedMarketingName'), '') else v_request.assigned_marketing_name end;
  v_marketing_notes := case when p_payload ? 'marketingNotes' then nullif(btrim(p_payload->>'marketingNotes'), '') else v_request.marketing_notes end;

  update public.marketing_requests
  set status = v_status,
      confirmed_capture_at = v_confirmed,
      promised_at = v_promised,
      assigned_marketing_name = v_assigned,
      marketing_notes = v_marketing_notes,
      completed_at = case when v_status in ('pronto', 'cancelado') then coalesce(completed_at, now()) else null end
  where id = p_request_id;

  insert into public.marketing_request_events(request_id, event_type, from_status, to_status, actor_user_id, actor_name, details)
  values (p_request_id, 'gestao_atualizada', v_request.status, v_status, v_user_id, v_user_name, p_payload);
end;
$$;

create or replace function public.marketing_save_access(
  p_access_code text,
  p_managed_user_id text,
  p_role text,
  p_team_id uuid default null,
  p_active boolean default true
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id text;
  v_role text;
begin
  select r.user_id, r.access_role into v_user_id, v_role
  from public.marketing_resolve_actor(p_access_code) r;
  if v_user_id is null or v_role <> 'admin' then raise exception 'MARKETING_ADMIN_REQUIRED'; end if;
  if p_role not in ('admin', 'marketing', 'sales_manager') then raise exception 'MARKETING_ROLE_INVALID'; end if;
  if p_role = 'sales_manager' and p_team_id is null then raise exception 'MARKETING_TEAM_REQUIRED'; end if;
  if not exists (select 1 from public.managed_users where id = p_managed_user_id and active is true) then
    raise exception 'MARKETING_USER_NOT_FOUND';
  end if;

  insert into public.marketing_access(managed_user_id, role, team_id, active)
  values (p_managed_user_id, p_role, case when p_role = 'sales_manager' then p_team_id else null end, coalesce(p_active, true))
  on conflict (managed_user_id) do update
    set role = excluded.role,
        team_id = excluded.team_id,
        active = excluded.active;
end;
$$;

alter table public.marketing_teams enable row level security;
alter table public.marketing_brokers enable row level security;
alter table public.marketing_access enable row level security;
alter table public.marketing_requests enable row level security;
alter table public.marketing_request_events enable row level security;

revoke all on public.marketing_teams from anon, authenticated;
revoke all on public.marketing_brokers from anon, authenticated;
revoke all on public.marketing_access from anon, authenticated;
revoke all on public.marketing_requests from anon, authenticated;
revoke all on public.marketing_request_events from anon, authenticated;

revoke all on function public.touch_marketing_updated_at() from public;
revoke all on function public.marketing_resolve_actor(text) from public;
revoke all on function public.marketing_get_dashboard(text) from public;
revoke all on function public.marketing_create_request(text, uuid, text, boolean, text, text, text[], text, timestamptz, text, boolean, text, boolean, text) from public;
revoke all on function public.marketing_update_request(text, uuid, text, jsonb) from public;
revoke all on function public.marketing_save_access(text, text, text, uuid, boolean) from public;

grant execute on function public.marketing_get_dashboard(text) to anon, authenticated;
grant execute on function public.marketing_create_request(text, uuid, text, boolean, text, text, text[], text, timestamptz, text, boolean, text, boolean, text) to anon, authenticated;
grant execute on function public.marketing_update_request(text, uuid, text, jsonb) to anon, authenticated;
grant execute on function public.marketing_save_access(text, text, text, uuid, boolean) to anon, authenticated;

notify pgrst, 'reload schema';
