alter table public.radio_playlist_tracks
  add column if not exists cleanup_after_play boolean not null default true;

alter table public.radio_playlist_sessions
  add column if not exists source_type text not null default 'temporary',
  add column if not exists source_id uuid,
  add column if not exists triggered_by text not null default 'manual';

alter table public.radio_playlist_sessions
  add constraint radio_playlist_sessions_source_type_check
  check (source_type in ('temporary','library_playlist','content_item'));

alter table public.radio_playlist_sessions
  add constraint radio_playlist_sessions_triggered_by_check
  check (triggered_by in ('manual','schedule'));

create table public.radio_library_playlists (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  title text not null check (char_length(btrim(title)) between 1 and 120),
  description text,
  is_archived boolean not null default false,
  play_count integer not null default 0 check (play_count >= 0),
  last_played_at timestamptz
);

create table public.radio_library_tracks (
  id uuid primary key default gen_random_uuid(),
  playlist_id uuid not null references public.radio_library_playlists(id) on delete cascade,
  position integer not null check (position between 1 and 100),
  file_name text not null check (char_length(btrim(file_name)) between 1 and 255),
  storage_path text not null unique,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes > 0),
  duration_seconds numeric(10,2) check (duration_seconds is null or duration_seconds > 0),
  created_at timestamptz not null default now(),
  unique (playlist_id, position)
);

create table public.radio_content_items (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  kind text not null check (kind in ('jingle','announcement','property','training','event')),
  title text not null check (char_length(btrim(title)) between 1 and 160),
  script_text text,
  status text not null default 'draft' check (status in ('draft','ready','archived')),
  audio_file_name text,
  audio_storage_path text unique,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes > 0),
  duration_seconds numeric(10,2) check (duration_seconds is null or duration_seconds > 0),
  property_code text,
  property_url text,
  metadata jsonb not null default '{}'::jsonb,
  play_count integer not null default 0 check (play_count >= 0),
  last_played_at timestamptz,
  check ((status <> 'ready') or audio_storage_path is not null)
);

create table public.radio_program_entries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  title text not null check (char_length(btrim(title)) between 1 and 160),
  target_type text not null check (target_type in ('playlist','content')),
  playlist_id uuid references public.radio_library_playlists(id) on delete restrict,
  content_id uuid references public.radio_content_items(id) on delete restrict,
  schedule_type text not null check (schedule_type in ('once','weekly')),
  run_at timestamptz,
  weekdays smallint[] not null default '{}'::smallint[],
  local_time time,
  timezone text not null default 'America/Sao_Paulo',
  active boolean not null default true,
  last_run_key text,
  last_run_at timestamptz,
  last_error text,
  check (
    (target_type = 'playlist' and playlist_id is not null and content_id is null)
    or (target_type = 'content' and content_id is not null and playlist_id is null)
  ),
  check (
    (schedule_type = 'once' and run_at is not null)
    or (schedule_type = 'weekly' and local_time is not null and cardinality(weekdays) > 0)
  ),
  check (weekdays <@ array[0,1,2,3,4,5,6]::smallint[])
);

create table public.radio_program_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  program_id uuid references public.radio_program_entries(id) on delete set null,
  session_id uuid references public.radio_playlist_sessions(id) on delete set null,
  status text not null check (status in ('queued','failed','skipped')),
  message text
);

create index radio_library_tracks_playlist_idx on public.radio_library_tracks(playlist_id, position);
create index radio_content_items_kind_status_idx on public.radio_content_items(kind, status, created_at desc);
create index radio_program_entries_active_idx on public.radio_program_entries(active, schedule_type);
create index radio_program_log_created_idx on public.radio_program_log(created_at desc);

alter table public.radio_library_playlists enable row level security;
alter table public.radio_library_tracks enable row level security;
alter table public.radio_content_items enable row level security;
alter table public.radio_program_entries enable row level security;
alter table public.radio_program_log enable row level security;

create policy radio_library_playlists_admin_all on public.radio_library_playlists
  for all to authenticated using (public.is_hub_admin()) with check (public.is_hub_admin());
create policy radio_library_tracks_admin_all on public.radio_library_tracks
  for all to authenticated using (public.is_hub_admin()) with check (public.is_hub_admin());
create policy radio_content_items_admin_all on public.radio_content_items
  for all to authenticated using (public.is_hub_admin()) with check (public.is_hub_admin());
create policy radio_program_entries_admin_all on public.radio_program_entries
  for all to authenticated using (public.is_hub_admin()) with check (public.is_hub_admin());
create policy radio_program_log_admin_select on public.radio_program_log
  for select to authenticated using (public.is_hub_admin());

create or replace function public.radio_touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger radio_library_playlists_touch_updated_at
before update on public.radio_library_playlists
for each row execute function public.radio_touch_updated_at();
create trigger radio_content_items_touch_updated_at
before update on public.radio_content_items
for each row execute function public.radio_touch_updated_at();
create trigger radio_program_entries_touch_updated_at
before update on public.radio_program_entries
for each row execute function public.radio_touch_updated_at();

create or replace function public.radio_create_library_playlist(
  p_id uuid,
  p_title text,
  p_description text,
  p_tracks jsonb
)
returns public.radio_library_playlists
language plpgsql
security definer
set search_path = public, storage, pg_temp
as $$
declare
  v_playlist public.radio_library_playlists%rowtype;
  v_track jsonb;
  v_count integer;
  v_position integer;
  v_file_name text;
  v_storage_path text;
  v_file_size bigint;
begin
  if auth.uid() is null or not public.is_hub_admin() then
    raise exception 'RADIO_ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if p_id is null then raise exception 'RADIO_LIBRARY_ID_REQUIRED' using errcode = '22023'; end if;
  if p_title is null or btrim(p_title) = '' then raise exception 'RADIO_LIBRARY_TITLE_REQUIRED' using errcode = '22023'; end if;
  if jsonb_typeof(p_tracks) <> 'array' then raise exception 'RADIO_LIBRARY_TRACKS_REQUIRED' using errcode = '22023'; end if;

  v_count := jsonb_array_length(p_tracks);
  if v_count < 1 or v_count > 30 then raise exception 'RADIO_LIBRARY_TRACK_COUNT_INVALID' using errcode = '22023'; end if;

  insert into public.radio_library_playlists (id, created_by, title, description)
  values (p_id, auth.uid(), left(btrim(p_title), 120), nullif(btrim(p_description), ''))
  returning * into v_playlist;

  for v_track in select value from jsonb_array_elements(p_tracks)
  loop
    v_position := nullif(v_track->>'position', '')::integer;
    v_file_name := nullif(btrim(v_track->>'file_name'), '');
    v_storage_path := nullif(btrim(v_track->>'storage_path'), '');
    v_file_size := nullif(v_track->>'file_size_bytes', '')::bigint;
    if v_position is null or v_position < 1 or v_position > 100 then raise exception 'RADIO_LIBRARY_POSITION_INVALID' using errcode = '22023'; end if;
    if v_file_name is null then raise exception 'RADIO_LIBRARY_FILE_NAME_REQUIRED' using errcode = '22023'; end if;
    if v_storage_path is null or v_storage_path not like ('library/' || p_id::text || '/%') then raise exception 'RADIO_LIBRARY_STORAGE_PATH_INVALID' using errcode = '22023'; end if;
    if not exists (select 1 from storage.objects o where o.bucket_id = 'radio-playlists' and o.name = v_storage_path) then raise exception 'RADIO_LIBRARY_FILE_NOT_FOUND' using errcode = '22023'; end if;
    insert into public.radio_library_tracks (playlist_id, position, file_name, storage_path, file_size_bytes)
    values (p_id, v_position, left(v_file_name,255), v_storage_path, v_file_size);
  end loop;
  return v_playlist;
end;
$$;

create or replace function public.radio_add_library_tracks(p_playlist_id uuid, p_tracks jsonb)
returns integer
language plpgsql
security definer
set search_path = public, storage, pg_temp
as $$
declare
  v_track jsonb;
  v_count integer;
  v_existing integer;
  v_position integer;
  v_file_name text;
  v_storage_path text;
  v_file_size bigint;
begin
  if auth.uid() is null or not public.is_hub_admin() then raise exception 'RADIO_ADMIN_REQUIRED' using errcode = '42501'; end if;
  if not exists (select 1 from public.radio_library_playlists p where p.id = p_playlist_id and not p.is_archived) then raise exception 'RADIO_LIBRARY_NOT_FOUND' using errcode = 'P0002'; end if;
  if jsonb_typeof(p_tracks) <> 'array' then raise exception 'RADIO_LIBRARY_TRACKS_REQUIRED' using errcode = '22023'; end if;
  v_count := jsonb_array_length(p_tracks);
  select count(*) into v_existing from public.radio_library_tracks where playlist_id = p_playlist_id;
  if v_count < 1 or v_existing + v_count > 30 then raise exception 'RADIO_LIBRARY_TRACK_COUNT_INVALID' using errcode = '22023'; end if;
  for v_track in select value from jsonb_array_elements(p_tracks)
  loop
    v_position := nullif(v_track->>'position','')::integer;
    v_file_name := nullif(btrim(v_track->>'file_name'),'');
    v_storage_path := nullif(btrim(v_track->>'storage_path'),'');
    v_file_size := nullif(v_track->>'file_size_bytes','')::bigint;
    if v_position is null or v_position < 1 or v_position > 100 then raise exception 'RADIO_LIBRARY_POSITION_INVALID' using errcode = '22023'; end if;
    if v_file_name is null then raise exception 'RADIO_LIBRARY_FILE_NAME_REQUIRED' using errcode = '22023'; end if;
    if v_storage_path is null or v_storage_path not like ('library/' || p_playlist_id::text || '/%') then raise exception 'RADIO_LIBRARY_STORAGE_PATH_INVALID' using errcode = '22023'; end if;
    if not exists (select 1 from storage.objects o where o.bucket_id='radio-playlists' and o.name=v_storage_path) then raise exception 'RADIO_LIBRARY_FILE_NOT_FOUND' using errcode = '22023'; end if;
    insert into public.radio_library_tracks (playlist_id,position,file_name,storage_path,file_size_bytes)
    values (p_playlist_id,v_position,left(v_file_name,255),v_storage_path,v_file_size);
  end loop;
  return v_count;
end;
$$;

create or replace function public.radio_reorder_library_playlist(p_playlist_id uuid, p_track_ids uuid[])
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_total integer;
  v_id uuid;
  v_position integer := 0;
begin
  if auth.uid() is null or not public.is_hub_admin() then raise exception 'RADIO_ADMIN_REQUIRED' using errcode='42501'; end if;
  select count(*) into v_total from public.radio_library_tracks where playlist_id=p_playlist_id;
  if v_total <> coalesce(cardinality(p_track_ids),0) then raise exception 'RADIO_LIBRARY_REORDER_INVALID' using errcode='22023'; end if;
  update public.radio_library_tracks set position = position + 1000 where playlist_id=p_playlist_id;
  foreach v_id in array p_track_ids loop
    v_position := v_position + 1;
    update public.radio_library_tracks set position=v_position where playlist_id=p_playlist_id and id=v_id;
    if not found then raise exception 'RADIO_LIBRARY_REORDER_INVALID' using errcode='22023'; end if;
  end loop;
  return true;
end;
$$;

create or replace function public.radio_remove_library_track(p_track_id uuid)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_playlist_id uuid;
  v_path text;
begin
  if auth.uid() is null or not public.is_hub_admin() then raise exception 'RADIO_ADMIN_REQUIRED' using errcode='42501'; end if;
  delete from public.radio_library_tracks where id=p_track_id returning playlist_id,storage_path into v_playlist_id,v_path;
  if not found then raise exception 'RADIO_LIBRARY_TRACK_NOT_FOUND' using errcode='P0002'; end if;
  with ranked as (
    select id,row_number() over(order by position,id)::integer as rn from public.radio_library_tracks where playlist_id=v_playlist_id
  )
  update public.radio_library_tracks t set position=ranked.rn+1000 from ranked where t.id=ranked.id;
  update public.radio_library_tracks set position=position-1000 where playlist_id=v_playlist_id;
  return v_path;
end;
$$;

create or replace function public.radio_enter_temporary_mode_internal(p_actor uuid)
returns public.radio_runtime_state
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_runtime public.radio_runtime_state%rowtype;
  v_player public.radio_player_state%rowtype;
begin
  select * into v_runtime from public.radio_runtime_state where id='main' for update;
  if v_runtime.operating_mode='temporary' then raise exception 'RADIO_TEMPORARY_MODE_ALREADY_ACTIVE' using errcode='55000'; end if;
  select * into v_player from public.radio_player_state where id='main';
  update public.radio_runtime_state
     set operating_mode='temporary', temporary_started_at=now(), temporary_started_by=p_actor,
         resume_on_exit=coalesce(v_player.player_status='play',false),
         saved_player_status=v_player.player_status, saved_title=v_player.title,
         saved_artist=v_player.artist, saved_album=v_player.album, saved_mode=v_player.mode,
         saved_current_ms=v_player.current_ms, saved_total_ms=v_player.total_ms, updated_at=now()
   where id='main' returning * into v_runtime;
  if v_runtime.resume_on_exit then insert into public.radio_player_commands(command,value) values('pause',null); end if;
  return v_runtime;
end;
$$;

create or replace function public.radio_launch_persistent_target_internal(p_target_type text, p_target_id uuid, p_triggered_by text, p_actor uuid)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_session_id uuid := gen_random_uuid();
  v_title text;
  v_track_count integer;
  v_content public.radio_content_items%rowtype;
begin
  if p_target_type not in ('playlist','content') then raise exception 'RADIO_TARGET_INVALID' using errcode='22023'; end if;
  if p_triggered_by not in ('manual','schedule') then raise exception 'RADIO_TRIGGER_INVALID' using errcode='22023'; end if;
  if exists (select 1 from public.radio_playlist_sessions s where s.status in ('queued','claimed','playing','stop_requested')) then raise exception 'RADIO_PLAYLIST_ALREADY_ACTIVE' using errcode='55000'; end if;
  if exists (select 1 from public.radio_runtime_state r where r.id='main' and r.operating_mode='temporary') then raise exception 'RADIO_TEMPORARY_MODE_ALREADY_ACTIVE' using errcode='55000'; end if;
  if p_target_type='playlist' then
    select p.title into v_title from public.radio_library_playlists p where p.id=p_target_id and not p.is_archived;
    if v_title is null then raise exception 'RADIO_LIBRARY_NOT_FOUND' using errcode='P0002'; end if;
    select count(*) into v_track_count from public.radio_library_tracks t where t.playlist_id=p_target_id;
    if v_track_count < 1 then raise exception 'RADIO_LIBRARY_EMPTY' using errcode='55000'; end if;
  else
    select * into v_content from public.radio_content_items c where c.id=p_target_id and c.status='ready';
    if not found or v_content.audio_storage_path is null then raise exception 'RADIO_CONTENT_NOT_READY' using errcode='55000'; end if;
    v_title := v_content.title;
  end if;
  perform public.radio_enter_temporary_mode_internal(p_actor);
  insert into public.radio_playlist_sessions(id,created_by,title,status,source_type,source_id,triggered_by)
  values(v_session_id,p_actor,left(v_title,120),'queued',case when p_target_type='playlist' then 'library_playlist' else 'content_item' end,p_target_id,p_triggered_by);
  if p_target_type='playlist' then
    insert into public.radio_playlist_tracks(session_id,position,file_name,storage_path,cleanup_after_play)
    select v_session_id,t.position,t.file_name,t.storage_path,false from public.radio_library_tracks t where t.playlist_id=p_target_id order by t.position;
    update public.radio_library_playlists set play_count=play_count+1,last_played_at=now() where id=p_target_id;
  else
    insert into public.radio_playlist_tracks(session_id,position,file_name,storage_path,cleanup_after_play)
    values(v_session_id,1,coalesce(v_content.audio_file_name,'conteudo.mp3'),v_content.audio_storage_path,false);
    update public.radio_content_items set play_count=play_count+1,last_played_at=now() where id=p_target_id;
  end if;
  return v_session_id;
end;
$$;

revoke all on function public.radio_enter_temporary_mode_internal(uuid) from public, anon, authenticated;
revoke all on function public.radio_launch_persistent_target_internal(text,uuid,text,uuid) from public, anon, authenticated;

create or replace function public.radio_start_library_playlist(p_playlist_id uuid)
returns public.radio_playlist_sessions
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_id uuid; v_session public.radio_playlist_sessions%rowtype;
begin
  if auth.uid() is null or not public.is_hub_admin() then raise exception 'RADIO_ADMIN_REQUIRED' using errcode='42501'; end if;
  v_id := public.radio_launch_persistent_target_internal('playlist',p_playlist_id,'manual',auth.uid());
  select * into v_session from public.radio_playlist_sessions where id=v_id;
  return v_session;
end;
$$;

create or replace function public.radio_start_content_item(p_content_id uuid)
returns public.radio_playlist_sessions
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_id uuid; v_session public.radio_playlist_sessions%rowtype;
begin
  if auth.uid() is null or not public.is_hub_admin() then raise exception 'RADIO_ADMIN_REQUIRED' using errcode='42501'; end if;
  v_id := public.radio_launch_persistent_target_internal('content',p_content_id,'manual',auth.uid());
  select * into v_session from public.radio_playlist_sessions where id=v_id;
  return v_session;
end;
$$;

create or replace function public.radio_process_program()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_entry public.radio_program_entries%rowtype;
  v_local timestamp;
  v_due boolean;
  v_run_key text;
  v_session_id uuid;
  v_target_id uuid;
begin
  if exists (select 1 from public.radio_playlist_sessions s where s.status in ('queued','claimed','playing','stop_requested')) then return 0; end if;
  if exists (select 1 from public.radio_runtime_state r where r.id='main' and r.operating_mode='temporary') then return 0; end if;
  for v_entry in select * from public.radio_program_entries p where p.active order by p.created_at
  loop
    v_due := false; v_run_key := null;
    if v_entry.schedule_type='once' then
      if v_entry.run_at <= now() and coalesce(v_entry.last_run_key,'') <> 'once' then v_due := true; v_run_key := 'once'; end if;
    else
      v_local := now() at time zone v_entry.timezone;
      v_run_key := to_char(v_local::date,'YYYY-MM-DD');
      if extract(dow from v_local)::smallint = any(v_entry.weekdays)
         and v_entry.local_time <= v_local::time
         and coalesce(v_entry.last_run_key,'') <> v_run_key then v_due := true; end if;
    end if;
    if v_due then
      v_target_id := case when v_entry.target_type='playlist' then v_entry.playlist_id else v_entry.content_id end;
      begin
        v_session_id := public.radio_launch_persistent_target_internal(v_entry.target_type,v_target_id,'schedule',null);
        update public.radio_program_entries set last_run_key=v_run_key,last_run_at=now(),last_error=null,active=case when schedule_type='once' then false else active end where id=v_entry.id;
        insert into public.radio_program_log(program_id,session_id,status,message) values(v_entry.id,v_session_id,'queued','Programação enviada para a Rádio Santa Maria.');
        return 1;
      exception when others then
        update public.radio_program_entries set last_run_key=v_run_key,last_run_at=now(),last_error=sqlerrm,active=case when schedule_type='once' then false else active end where id=v_entry.id;
        insert into public.radio_program_log(program_id,status,message) values(v_entry.id,'failed',sqlerrm);
        return 0;
      end;
    end if;
  end loop;
  return 0;
end;
$$;

revoke all on function public.radio_process_program() from public, anon, authenticated;

do $$
declare v_jobid bigint;
begin
  select jobid into v_jobid from cron.job where jobname='radio-program-every-minute' limit 1;
  if v_jobid is not null then perform cron.unschedule(v_jobid); end if;
  perform cron.schedule('radio-program-every-minute','* * * * *','select public.radio_process_program();');
end;
$$;

grant execute on function public.radio_create_library_playlist(uuid,text,text,jsonb) to authenticated;
grant execute on function public.radio_add_library_tracks(uuid,jsonb) to authenticated;
grant execute on function public.radio_reorder_library_playlist(uuid,uuid[]) to authenticated;
grant execute on function public.radio_remove_library_track(uuid) to authenticated;
grant execute on function public.radio_start_library_playlist(uuid) to authenticated;
grant execute on function public.radio_start_content_item(uuid) to authenticated;
